// contract/codegen:从 contract/contract.v1.json 生成 Go 类型与 TS 常量。
//
// 用法(仓库根目录执行):
//
//	go run ./contract/codegen          生成(覆盖 contract/gen/ 下产物)
//	go run ./contract/codegen -check   校验产物与契约一致(CI 用;漂移退出码 1)
//
// 生成规则:
//   - 只生成机器可判定的部分:枚举、常量、元数据表、信封结构、默认参数、各 kind 的线上字段名清单。
//   - 契约中 "$" 开头的键是文档注释,不进产物;各对象里的散文字段(note/redispatch 等)不进产物。
//   - 产物确定性:键一律排序、无时间戳;ContractHash = sha256(契约文件原始字节)。
package main

import (
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

var (
	contractPath = flag.String("contract", "contract/contract.v1.json", "契约文件路径")
	goOut        = flag.String("go-out", "contract/gen/go/protocol/protocol.gen.go", "Go 产物路径")
	tsOut        = flag.String("ts-out", "contract/gen/ts/protocol.gen.ts", "TS 产物路径")
	check        = flag.Bool("check", false, "只校验产物是否与契约一致,不写文件")
)

func main() {
	flag.Parse()

	raw, err := os.ReadFile(*contractPath)
	must(err, "读契约文件")
	var c map[string]any
	must(json.Unmarshal(raw, &c), "解析契约 JSON")

	hash := fmt.Sprintf("sha256:%x", sha256.Sum256(raw))
	assertContract(c)

	goSrc := genGo(c, hash)
	tsSrc := genTS(c, hash)

	formatted, err := format.Source(goSrc)
	if err != nil {
		fmt.Fprintln(os.Stderr, "生成的 Go 源码无法通过 gofmt(生成器 bug):", err)
		fmt.Fprintln(os.Stderr, withLineNumbers(string(goSrc)))
		os.Exit(1)
	}

	outputs := []struct {
		path string
		data []byte
	}{
		{*goOut, formatted},
		{*tsOut, tsSrc},
	}

	if *check {
		drift := false
		for _, o := range outputs {
			existing, err := os.ReadFile(o.path)
			switch {
			case err != nil:
				fmt.Printf("缺失: %s\n", o.path)
				drift = true
			case string(existing) != string(o.data):
				fmt.Printf("漂移: %s(请重跑 go run ./contract/codegen)\n", o.path)
				drift = true
			default:
				fmt.Printf("一致: %s\n", o.path)
			}
		}
		if drift {
			os.Exit(1)
		}
		return
	}

	for _, o := range outputs {
		must(os.MkdirAll(filepath.Dir(o.path), 0o755), "建目录")
		must(os.WriteFile(o.path, o.data, 0o644), "写 "+o.path)
		fmt.Printf("生成: %s(%d 字节)\n", o.path, len(o.data))
	}
}

// ---------- 契约一致性断言(生成前置检查) ----------

func assertContract(c map[string]any) {
	// 信封字段集必须与生成器映射表一致——契约加了信封字段而生成器不知道,必须响亮失败。
	envFields := obj(obj(c, "envelope"), "fields")
	want := map[string]bool{"proto": true, "kind": true, "msgId": true, "session": true, "ts": true, "attempt": true, "body": true}
	for k := range envFields {
		if !want[k] {
			die("契约 envelope.fields 出现生成器不认识的字段 %q:请同步更新 codegen 的信封映射", k)
		}
	}
	for k := range want {
		if _, ok := envFields[k]; !ok {
			die("契约 envelope.fields 缺少字段 %q", k)
		}
	}
	// kinds.report.states 与 enums.reportState 必须一致(同一事实只许一处定义的例外,双写必须相等)。
	rs := strSlice(obj(obj(c, "kinds"), "report")["states"])
	es := strSlice(obj(c, "enums")["reportState"])
	if strings.Join(rs, ",") != strings.Join(es, ",") {
		die("kinds.report.states 与 enums.reportState 不一致:%v vs %v", rs, es)
	}
}

// ---------- Go 产物 ----------

func genGo(c map[string]any, hash string) []byte {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("// Code generated by contract/codegen from %s. DO NOT EDIT.", *contractPath)
	w("")
	w("package protocol")
	w("")
	w(`import "encoding/json"`)
	w("")
	w("// 协议主版本与契约指纹")
	w("const (")
	w("\tProtoVersion = %d", intval(c["proto"]))
	w("\tContractHash = %q", hash)
	w(")")
	w("")

	tr := obj(c, "transport")
	w("// 传输常量")
	w("const (")
	w("\tTransportScheme  = %q", str(tr["scheme"]))
	w("\tTransportHost    = %q", str(tr["host"]))
	w("\tDefaultPort      = %d", intval(tr["portDefault"]))
	w("\tTransportPath    = %q", str(tr["path"]))
	w("\tOriginPrefix     = %q", str(tr["originPrefix"]))
	w("\tChromeMinVersion = %d", intval(tr["chromeMin"]))
	w(")")
	w("")

	// 枚举(enums 区,含 Batch/AckStatus/ResultStatus/Retryable/SideEffect/ReportState/NotReadyReason)
	enums := obj(c, "enums")
	for _, name := range sortedKeys(enums) {
		typ := pascal(name)
		vals := strSlice(enums[name])
		w("type %s string", typ)
		w("")
		w("const (")
		for _, v := range vals {
			w("\t%s%s %s = %q", typ, pascal(v), typ, v)
		}
		w(")")
		w("")
		w("var %sValues = []%s{", typ, typ)
		for _, v := range vals {
			w("\t%s%s,", typ, pascal(v))
		}
		w("}")
		w("")
	}

	// Kind
	kinds := obj(c, "kinds")
	w("type Kind string")
	w("")
	w("const (")
	for _, k := range sortedKeys(kinds) {
		w("\tKind%s Kind = %q", pascal(k), k)
	}
	w(")")
	w("")
	w("// KindMeta:方向、应答方、批次、是否可丢(lossy)。")
	w("type KindMeta struct {")
	w("\tDir   string // H2B / B2H / both")
	w("\tAckBy string // 应答该消息的 kind;空=无应答")
	w("\tBatch Batch")
	w("\tLossy bool // true=可丢(无重发、无补投)")
	w("}")
	w("")
	w("var Kinds = map[Kind]KindMeta{")
	for _, k := range sortedKeys(kinds) {
		m := obj(kinds, k)
		w("\tKind%s: {Dir: %q, AckBy: %q, Batch: Batch%s, Lossy: %t},",
			pascal(k), str(m["dir"]), str(m["ackBy"]), pascal(str(m["batch"])), boolval(m["lossy"]))
	}
	w("}")
	w("")

	// 信封
	w("// Envelope:所有消息的信封(7 字段,冻结;扩展只进 Body)。")
	w("type Envelope struct {")
	w("\tProto   int             `json:\"proto\"`")
	w("\tKind    Kind            `json:\"kind\"`")
	w("\tMsgID   string          `json:\"msgId\"`")
	w("\tSession *string         `json:\"session\"` // hello/welcome/bye 与 pre-session ping/pong 为 null")
	w("\tTs      int64           `json:\"ts\"`")
	w("\tAttempt int             `json:\"attempt\"`")
	w("\tBody    json.RawMessage `json:\"body\"`")
	w("}")
	w("")

	// 命令分类
	classes := obj(c, "classes")
	classKeys := objectKeys(classes)
	w("type CmdClass string")
	w("")
	w("const (")
	for _, k := range classKeys {
		w("\tClass%s CmdClass = %q", pascal(k), k)
	}
	w(")")
	w("")
	w("type ClassMeta struct {")
	w("\tSerialDomain bool   // 是否进串行域(账号域;debug.* 用每手 debug 域)")
	w("\tIdemKey      string // forbidden / required")
	w("\tEvidence     string")
	w("}")
	w("")
	w("var Classes = map[CmdClass]ClassMeta{")
	for _, k := range classKeys {
		m := obj(classes, k)
		w("\tClass%s: {SerialDomain: %t, IdemKey: %q, Evidence: %q},",
			pascal(k), boolval(m["serialDomain"]), str(m["idemKey"]), str(m["evidence"]))
	}
	w("}")
	w("")

	// bye 码
	byeCodes := strSlice(c["byeCodes"])
	w("type ByeCode string")
	w("")
	w("const (")
	for _, v := range byeCodes {
		w("\tByeCode%s ByeCode = %q", pascal(v), v)
	}
	w(")")
	w("")

	// 错误码
	errCodes := obj(c, "errorCodes")
	w("type ErrorCode string")
	w("")
	w("const (")
	for _, k := range sortedKeys(errCodes) {
		w("\tErrCode%s ErrorCode = %q", pascal(k), k)
	}
	w(")")
	w("")
	w("// ErrorCodeMeta:契约默认值。RetryableDefault 可为条件式描述(如 \"afterRecovery|manualOnly(SX)\"),裁决权在脑的矩阵。")
	w("type ErrorCodeMeta struct {")
	w("\tRetryableDefault string")
	w("\tSideEffect       []SideEffect // 允许取值")
	w("\tBatch            Batch")
	w("}")
	w("")
	w("var ErrorCodes = map[ErrorCode]ErrorCodeMeta{")
	for _, k := range sortedKeys(errCodes) {
		m := obj(errCodes, k)
		ses := strSlice(m["sideEffect"])
		parts := make([]string, len(ses))
		for i, se := range ses {
			parts[i] = "SideEffect" + pascal(se)
		}
		w("\tErrCode%s: {RetryableDefault: %q, SideEffect: []SideEffect{%s}, Batch: Batch%s},",
			pascal(k), str(m["retryable"]), strings.Join(parts, ", "), pascal(str(m["batch"])))
	}
	w("}")
	w("")

	// 原语
	prims := obj(c, "primitives")
	w("const (")
	for _, k := range sortedKeys(prims) {
		w("\tPrim%s = %q", pascal(k), k)
	}
	w(")")
	w("")
	w("type PrimitiveMeta struct {")
	w("\tVer                int // 0=占位,未定稿")
	w("\tClass              CmdClass")
	w("\tBatch              Batch")
	w("\tPlatformSideEffect string // intrusive 专用声明;空=未声明")
	w("\tExecBudgetMs       int64  // 0=用类默认")
	w("\tDeadlineMs         int64  // 0=派发时计算")
	w("}")
	w("")
	w("var Primitives = map[string]PrimitiveMeta{")
	for _, k := range sortedKeys(prims) {
		m := obj(prims, k)
		w("\tPrim%s: {Ver: %d, Class: Class%s, Batch: Batch%s, PlatformSideEffect: %q, ExecBudgetMs: %d, DeadlineMs: %d},",
			pascal(k), intval(m["ver"]), pascal(str(m["class"])), pascal(str(m["batch"])),
			str(m["platformSideEffect"]), intval(m["execBudgetMs"]), intval(m["deadlineMs"]))
	}
	w("}")
	w("")

	// 事件
	events := obj(c, "events")
	w("const (")
	for _, k := range sortedKeys(events) {
		w("\tEvent%s = %q", pascal(k), k)
	}
	w(")")
	w("")
	w("var Events = map[string]Batch{")
	for _, k := range sortedKeys(events) {
		w("\tEvent%s: Batch%s,", pascal(k), pascal(str(obj(events, k)["batch"])))
	}
	w("}")
	w("")

	// 默认参数(展平)
	w("// 默认参数(契约 defaults 展平;嵌套层级用驼峰连接)。welcome 可下发覆盖。")
	var consts, vars []string
	flattenDefaults("Default", obj(c, "defaults"), &consts, &vars)
	w("const (")
	for _, line := range consts {
		w("\t%s", line)
	}
	w(")")
	w("")
	for _, line := range vars {
		w("%s", line)
	}
	w("")

	// 各 kind 的线上字段名清单
	bodies := obj(c, "bodies")
	w("// KindBodyFields:各 kind 的线上字段名清单($ 注释键已剔除)。")
	w("// 用途:两端对手写 body 结构做一致性测试(json tag 必须与此表一致)。")
	w("var KindBodyFields = map[Kind][]string{")
	for _, k := range sortedKeys(bodies) {
		fields := wireFields(obj(bodies, k))
		quoted := make([]string, len(fields))
		for i, f := range fields {
			quoted[i] = strconv.Quote(f)
		}
		w("\tKind%s: {%s},", pascal(k), strings.Join(quoted, ", "))
	}
	w("}")

	return []byte(b.String())
}

// ---------- TS 产物 ----------

func genTS(c map[string]any, hash string) []byte {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("// Code generated by contract/codegen from %s. DO NOT EDIT.", *contractPath)
	w("")
	w("export const PROTO_VERSION = %d;", intval(c["proto"]))
	w("export const CONTRACT_HASH = %q;", hash)
	w("")

	tr := obj(c, "transport")
	w("export const TRANSPORT = {")
	w("  scheme: %q,", str(tr["scheme"]))
	w("  host: %q,", str(tr["host"]))
	w("  portDefault: %d,", intval(tr["portDefault"]))
	w("  path: %q,", str(tr["path"]))
	w("  originPrefix: %q,", str(tr["originPrefix"]))
	w("  chromeMinVersion: %d,", intval(tr["chromeMin"]))
	w("} as const;")
	w("")

	emitTSEnum := func(typ string, vals []string) {
		w("export const %s = {", typ)
		for _, v := range vals {
			w("  %s: %q,", pascal(v), v)
		}
		w("} as const;")
		w("export type %s = (typeof %s)[keyof typeof %s];", typ, typ, typ)
		w("")
	}

	enums := obj(c, "enums")
	for _, name := range sortedKeys(enums) {
		emitTSEnum(pascal(name), strSlice(enums[name]))
	}

	kinds := obj(c, "kinds")
	emitTSEnum("Kind", sortedKeys(kinds))

	w("export interface Envelope {")
	w("  proto: number;")
	w("  kind: Kind;")
	w("  msgId: string;")
	w("  /** hello/welcome/bye 与 pre-session ping/pong 为 null */")
	w("  session: string | null;")
	w("  ts: number;")
	w("  attempt: number;")
	w("  body: unknown;")
	w("}")
	w("")

	w("export interface KindMetaEntry {")
	w("  dir: \"H2B\" | \"B2H\" | \"both\";")
	w("  /** 应答该消息的 kind;null=无应答 */")
	w("  ackBy: string | null;")
	w("  batch: Batch;")
	w("  /** true=可丢(无重发、无补投) */")
	w("  lossy: boolean;")
	w("}")
	w("export const KIND_META: Record<Kind, KindMetaEntry> = {")
	for _, k := range sortedKeys(kinds) {
		m := obj(kinds, k)
		ackBy := "null"
		if s := str(m["ackBy"]); s != "" {
			ackBy = strconv.Quote(s)
		}
		w("  %s: { dir: %q, ackBy: %s, batch: %q, lossy: %t },", k, str(m["dir"]), ackBy, str(m["batch"]), boolval(m["lossy"]))
	}
	w("};")
	w("")

	classes := obj(c, "classes")
	classKeys := objectKeys(classes)
	emitTSEnum("CmdClass", classKeys)
	w("export interface ClassMetaEntry {")
	w("  /** 是否进串行域(账号域;debug.* 用每手 debug 域) */")
	w("  serialDomain: boolean;")
	w("  idemKey: \"forbidden\" | \"required\";")
	w("  evidence: string;")
	w("}")
	w("export const CLASS_META: Record<CmdClass, ClassMetaEntry> = {")
	for _, k := range classKeys {
		m := obj(classes, k)
		w("  %s: { serialDomain: %t, idemKey: %q, evidence: %q },", k, boolval(m["serialDomain"]), str(m["idemKey"]), str(m["evidence"]))
	}
	w("};")
	w("")

	emitTSEnum("ByeCode", strSlice(c["byeCodes"]))

	errCodes := obj(c, "errorCodes")
	emitTSEnum("ErrorCode", sortedKeys(errCodes))
	w("export interface ErrorCodeMetaEntry {")
	w("  /** 契约默认建议,可为条件式描述;裁决权在脑的矩阵 */")
	w("  retryableDefault: string;")
	w("  sideEffect: readonly SideEffect[];")
	w("  batch: Batch;")
	w("}")
	w("export const ERROR_CODE_META: Record<ErrorCode, ErrorCodeMetaEntry> = {")
	for _, k := range sortedKeys(errCodes) {
		m := obj(errCodes, k)
		ses := strSlice(m["sideEffect"])
		quoted := make([]string, len(ses))
		for i, se := range ses {
			quoted[i] = strconv.Quote(se)
		}
		w("  %s: { retryableDefault: %q, sideEffect: [%s], batch: %q },", k, str(m["retryable"]), strings.Join(quoted, ", "), str(m["batch"]))
	}
	w("};")
	w("")

	prims := obj(c, "primitives")
	emitTSEnum("Primitive", sortedKeys(prims))
	w("export interface PrimitiveMetaEntry {")
	w("  /** 0=占位,未定稿 */")
	w("  ver: number;")
	w("  class: CmdClass;")
	w("  batch: Batch;")
	w("  /** intrusive 专用声明;null=未声明 */")
	w("  platformSideEffect: string | null;")
	w("  /** null=用类默认 */")
	w("  execBudgetMs: number | null;")
	w("  /** null=派发时计算 */")
	w("  deadlineMs: number | null;")
	w("}")
	w("export const PRIMITIVE_META: Record<Primitive, PrimitiveMetaEntry> = {")
	for _, k := range sortedKeys(prims) {
		m := obj(prims, k)
		w("  %q: { ver: %d, class: %q, batch: %q, platformSideEffect: %s, execBudgetMs: %s, deadlineMs: %s },",
			k, intval(m["ver"]), str(m["class"]), str(m["batch"]),
			tsNullableStr(m["platformSideEffect"]), tsNullableInt(m["execBudgetMs"]), tsNullableInt(m["deadlineMs"]))
	}
	w("};")
	w("")

	events := obj(c, "events")
	emitTSEnum("EventName", sortedKeys(events))
	w("export const EVENT_META: Record<EventName, { batch: Batch }> = {")
	for _, k := range sortedKeys(events) {
		w("  %s: { batch: %q },", k, str(obj(events, k)["batch"]))
	}
	w("};")
	w("")

	// 默认参数:原样嵌入(键排序的 JSON)
	defJSON, err := json.MarshalIndent(sortValue(obj(c, "defaults")), "", "  ")
	must(err, "序列化 defaults")
	w("/** 默认参数(welcome 可下发覆盖) */")
	w("export const DEFAULTS = %s as const;", string(defJSON))
	w("")

	bodies := obj(c, "bodies")
	w("/** 各 kind 的线上字段名清单($ 注释键已剔除);用于 body 结构一致性测试 */")
	w("export const KIND_BODY_FIELDS: Record<Kind, readonly string[]> = {")
	for _, k := range sortedKeys(bodies) {
		fields := wireFields(obj(bodies, k))
		quoted := make([]string, len(fields))
		for i, f := range fields {
			quoted[i] = strconv.Quote(f)
		}
		w("  %s: [%s],", k, strings.Join(quoted, ", "))
	}
	w("};")

	return []byte(b.String())
}

// ---------- 小工具 ----------

func must(err error, what string) {
	if err != nil {
		die("%s: %v", what, err)
	}
}

func die(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "codegen: "+f+"\n", a...)
	os.Exit(1)
}

func obj(m map[string]any, key string) map[string]any {
	v, ok := m[key].(map[string]any)
	if !ok {
		die("契约缺少对象 %q", key)
	}
	return v
}

func str(v any) string {
	if v == nil {
		return ""
	}
	s, ok := v.(string)
	if !ok {
		die("期望字符串,得到 %T(%v)", v, v)
	}
	return s
}

func intval(v any) int64 {
	if v == nil {
		return 0
	}
	f, ok := v.(float64)
	if !ok || f != math.Trunc(f) {
		die("期望整数,得到 %T(%v)", v, v)
	}
	return int64(f)
}

func boolval(v any) bool {
	b, _ := v.(bool)
	return b
}

func strSlice(v any) []string {
	arr, ok := v.([]any)
	if !ok {
		die("期望数组,得到 %T", v)
	}
	out := make([]string, len(arr))
	for i, x := range arr {
		out[i] = str(x)
	}
	return out
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// objectKeys:值为对象的键(排序),用于跳过同级散文字段(litmus 等)。
func objectKeys(m map[string]any) []string {
	var keys []string
	for k, v := range m {
		if _, ok := v.(map[string]any); ok {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	return keys
}

// wireFields:剔除 $ 前缀注释键后的字段名(排序)。
func wireFields(m map[string]any) []string {
	var keys []string
	for k := range m {
		if !strings.HasPrefix(k, "$") {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	return keys
}

// pascal:proto_malformed / debug.ping / hbIntervalMs / AUTH_FAILED -> ProtoMalformed / DebugPing / HbIntervalMs / AuthFailed
func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '.' || r == '_' || r == '-' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if p == strings.ToUpper(p) {
			p = strings.ToLower(p)
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func tsNullableStr(v any) string {
	if v == nil {
		return "null"
	}
	return strconv.Quote(str(v))
}

func tsNullableInt(v any) string {
	if v == nil {
		return "null"
	}
	return strconv.FormatInt(intval(v), 10)
}

// flattenDefaults:defaults 嵌套展平为 Go 常量/变量行。
func flattenDefaults(prefix string, m map[string]any, consts, vars *[]string) {
	for _, k := range sortedKeys(m) {
		name := prefix + pascal(k)
		switch v := m[k].(type) {
		case float64:
			if v == math.Trunc(v) {
				*consts = append(*consts, fmt.Sprintf("%s = %d", name, int64(v)))
			} else {
				*consts = append(*consts, fmt.Sprintf("%s = %s", name, strconv.FormatFloat(v, 'g', -1, 64)))
			}
		case map[string]any:
			flattenDefaults(name, v, consts, vars)
		case []any:
			nums := make([]string, len(v))
			for i, x := range v {
				nums[i] = strconv.FormatInt(intval(x), 10)
			}
			*vars = append(*vars, fmt.Sprintf("var %s = []int{%s}", name, strings.Join(nums, ", ")))
		default:
			die("defaults.%s 是不支持的类型 %T", k, v)
		}
	}
}

// sortValue:递归把 map 换成排序后的有序输出(json.Marshal 对 map 本就按键排序,这里处理嵌套数组内的 map)。
func sortValue(v any) any { return v }

func withLineNumbers(src string) string {
	lines := strings.Split(src, "\n")
	var b strings.Builder
	for i, l := range lines {
		fmt.Fprintf(&b, "%4d  %s\n", i+1, l)
	}
	return b.String()
}
